apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argovue.fullname" . }}
  labels:
    {{- include "argovue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "argovue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argovue.selectorLabels" . | nindent 8 }}
      {{- with .Values.argovue.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "argovue.serviceAccountName" . }}
      volumes:
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 6 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./argovue"]
          volumeMounts:
{{- if .Values.mounts }}
{{ toYaml .Values.mounts | indent 10 }}
{{- end }}
          env:
            - name: VERBOSE
              value: {{ .Values.argovue.verbose }}
            - name: SESSION_KEY
              value: {{ randAlphaNum 16 }}
            - name: OIDC_PROVIDER
              value: {{ .Values.argovue.oidcProvider }}
            - name: OIDC_REDIRECT_URL
              value: {{ .Values.argovue.oidcRedirectUrl }}
            - name: OIDC_SCOPE
              value: {{ .Values.argovue.oidcScope }}
            - name: UI_ROOT_URL
              value: {{ .Values.argovue.uiRootUrl }}
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: K8S_RELEASE_NAME
              value: {{ include "argovue.fullname" . }}
            - name: K8S_SERVICE_NAME
              value: {{ include "argovue.fullname" . }}
            - name: DEX_SERVICE_NAME
              value: {{ include "argovue.fullname" . }}-dex
            - name: BASE_DOMAIN
              value: {{ .Values.argovue.baseDomain }}
            - name: REDIS_ADDR
              value: {{ .Values.argovue.redisAddr | default (printf "%s-redis-master:6379" (include "argovue.fullname" .)) }}
            {{- toYaml .Values.argovue.env | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
