apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.argovue.io
spec:
  group: argovue.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: appconfigs
    singular: appconfig
    kind: AppConfig
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            groups:
              type: array
              items:
                type: object
                properties:
                  oidc:
                    type: string
                  kubernetes:
                    type: string