apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tokens.argovue.io
spec:
  group: argovue.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: tokens
    singular: token
    kind: Token
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            value:
              type: string
            description:
              type: string