replicaCount: 1

image:
  repository: jamhed/vaultlink

vaultlink:
  verbose: debug
  clusterName: ~
  vaultAddr: ~
  authPath: ~
  kubeApiAddr: ~

serviceAccount:
  create: false

volumes:
- name: ca-certificates
  configMap:
    name: ca-certificates
mounts:
- name: ca-certificates
  mountPath: /etc/ssl/certs
  readOnly: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
