apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
