replicaCount: 1

image:
  repository: jamhed/argovue
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: tpp-venafi-issuer
  hosts:
  - ~

argovue:
  verbose: debug
  oidcClientId: argovue
  oidcClientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
  oidcProvider: ~
  oidcRedirectUrl: ~
  oidcScope: groups
  uiRootUrl: ~
  baseDomain: ~
  groups:
  - oidc: authors
    kubernetes: authors

#volumes:
#- name: ca-certificates
#  configMap:
#    name: ca-certificates

#mounts:
#- name: ca-certificates
#  mountPath: /etc/ssl/certs
#  readOnly: true

dex:
  enabled: true
  logger:
    level: debug
  issuer: ~
  connectors:
  - type: mockCallback
    id: mock
    name: Example
  oauth2:
    skipApprovalScreen: true
  staticClients:
  - id: argovue
    redirectURIs:
    - ~
    name: 'ArgoVue'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  enablePasswordDB: true
  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
