apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    {{ .Values.argovue.ownerLabel }}: {{ .Values.argovue.owner }}
  labels:
    {{- toYaml .Values.argovue.labels | nindent 4 }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{ .Values.argovue.ownerLabel }}: {{ .Values.argovue.owner }}
      labels:
        {{- toYaml .Values.argovue.labels | nindent 8 }}
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        {{- if .Values.command }}
        command:
        {{- range $i, $cmd := .Values.command }}
        - {{ $cmd }}
        {{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        volumeMounts:
        {{- if .Values.privateVolumeSize }}
        - mountPath: /mnt/private
          name: private
        {{- end }}
        env:
        - name: BASE_URL
          value: {{ .Values.argovue.baseurl }}
        {{- with .Values.argovue.input }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.privateVolumeSize }}
      - name: private
        persistentVolumeClaim:
          claimName: {{ template "chart.fullname" . }}
      {{- end }}
