{{- if .Values.privateVolumeSize }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}
  annotations:
    {{ .Values.argovue.ownerLabel }}: {{ .Values.argovue.owner }}
  labels:
    {{- toYaml .Values.argovue.labels | nindent 4 }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.privateVolumeSize | quote }}
{{- if .Values.storageClass }}
{{- if (eq "-" .Values.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
