apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    {{ .Values.argovue.ownerLabel }}: {{ .Values.argovue.owner }}
  labels:
    {{- toYaml .Values.argovue.labels | nindent 4 }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
